name: firebase_logger
description: An extension for logger that logs to Firebase Crashlytics
version: 1.0.3
repository: https://github.com/percula/firebase_logger

environment:
  sdk: '>=2.16.2 <4.0.0'

dependencies:
  logger: '>=2.1.0 <3.0.0'
  firebase_crashlytics: '>=2.5.0 <6.0.0'
